# Generated by Django 3.2.25 on 2026-04-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tarefa',
            name='tarefas_tar_user_id_3acb3b_idx',
        ),
        migrations.RemoveIndex(
            model_name='tarefa',
            name='tarefas_tar_user_id_8511b7_idx',
        ),
        migrations.RemoveIndex(
            model_name='tarefa',
            name='tarefas_tar_user_id_72bb0e_idx',
        ),
        migrations.RemoveIndex(
            model_name='tarefa',
            name='tarefas_tar_user_id_7dfd02_idx',
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['user', 'status'], name='tarefas_tar_user_id_6916b4_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['user', 'prioridade'], name='tarefas_tar_user_id_f019b4_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['user', 'arquivada'], name='tarefas_tar_user_id_632788_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['user', 'data_limite'], name='tarefas_tar_user_id_e4ea09_idx'),
        ),
    ]
