# Generated by Django 3.2.25 on 2026-04-28 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_auto_20260428_0741'),
        ('tarefas', '0002_tarefaauditlog'),
    ]

    operations = [
    ]
