# Generated by Django 3.2.25 on 2026-04-28 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_merge_0002_auto_20260428_0741_0002_tarefaauditlog'),
        ('tarefas', '0003_tarefa_empresa'),
    ]

    operations = [
    ]
