# Generated by Django 5.0.6 on 2026-06-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0005_assignment_and_notifications'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificacao',
            new_name='tarefas_not_user_id_0eaafd_idx',
            old_name='tarefas_not_user_id_6f0a8a_idx',
        ),
        migrations.RenameIndex(
            model_name='notificacao',
            new_name='tarefas_not_user_id_32bf24_idx',
            old_name='tarefas_not_user_id_2f3b1c_idx',
        ),
        migrations.RenameIndex(
            model_name='tarefa',
            new_name='tarefas_tar_assigne_587bff_idx',
            old_name='tarefas_tar_assigne_91c2ab_idx',
        ),
        migrations.RenameIndex(
            model_name='tarefa',
            new_name='tarefas_tar_assigne_3a6fdb_idx',
            old_name='tarefas_tar_assigne_4d8e12_idx',
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
