# Generated by Django 3.2.25 on 2024-05-29 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="email",
        ),
    ]
